config/routes.rb
Rails.application.routes.draw do
  resources :departamentos, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :produtos, only: [:new, :create, :destroy, :edit, :update]
  get "/produtos/busca" => "produtos#busca", as: :busca_produto
  root "produtos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
    belongs_to :departamento
    validates :quantidade, :preco, :nome, :descricao, presence: true
    validates :nome, length: { minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController

    before_action :set_departamento, only: [:edit, :update, :destroy]

    def index
        @departamentos = Departamento.all
    end

    def new
        @departamento = Departamento.new
    end

    def edit
        render :edit
    end

    def update
        if @departamento.update(params_departamento)
            flash[:notie] = "Departamento Atualizado com sucesso"
            redirect_to departamentos_path
        else
            render :edit
        end
    end

    def create
        @departamento = Departamento.new params_departamento
        if @departamento.save
            flash[:notice] = "Departamento criado com sucesso"
            redirect_to @departamento
        else
            render :new
        end
    end
    def show
        @departamento = Departamento.find(params[:id])
    end

    def destroy
        @departamento.destroy
        redirect_to departamentos_path
    end

    private

    def params_departamento
        params.require(:departamento).permit :nome
    end

    def set_departamento
        id = params[:id]
        @departamento = Departamento.find(id)
    end

end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

    before_action :set_produto, only: [:edit, :update, :destroy]
    
    def index
        @produtos_por_nome = Produto.all.order(:nome).limit 10
        @produtos_por_preco = Produto.all.order(:preco).limit 2
    end

    def new
        @produto = Produto.new
        @departamentos = Departamento.all
    end

    def edit
        @departamentos = Departamento.all
        render :edit
    end

    def update
        if @produto.update(params_produto)
            flash[:notice] = "Produto Atualizado com sucesso"
            redirect_to root_url
        else
            @departamentos = Departamento.all
            render :edit
        end
    end

    def busca
        @nome_a_buscar = params[:nome]
        @produtos = Produto.where "nome like ?", "%#{@nome_a_buscar}%"
    end

    def create
        @produto = Produto.new(params_produto)
        if @produto.save
            flash[:notice] = "Produto criado com sucesso"
            redirect_to root_url
        else
            @departamentos = Departamento.all
            render :new
        end
    end

    def destroy
        @produto.destroy
        flash[:notice] = "Produto removido com sucesso"
        redirect_to root_url
    end

    private

    def set_produto
        id = params[:id]
        @produto = Produto.find(id)
    end

    def params_produto
        params.require(:produto).permit :nome, :preco, :descricao, :quantidade, :departamento_id
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_for @departamento do |form| %>
    <div class="form-group">
        <%= form.label :departamento %>
        <%= form.text_field :nome, class: "form-control" %>
    </div>
    <%= form.submit texto_da_acao, class: "btn btn-primary" %>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editando departamento</h1>

<%= render partial: "form", locals: {texto_da_acao: "Editar Departamento" } %>

app/views/departamentos/index.html.erb
<h1>Departamentos</h1>

<% @departamentos.each do |departamento| %>
    <tr>
        <td><%= departamento.nome%></td>
    </tr><br>
    <td><%= button_to "Remove", departamento, method: :delete, class: "btn btn-danger", 
        data: {confirm: "Tem certeza que deseja remover #{departamento.nome}?"} %></td><br>
    <td>
        <%= link_to "Editar Departamento", edit_departamento_path(departamento), 
        class: "btn btn-primary" %><br>
    </td><br>
<% end %>

app/views/departamentos/new.html.erb
<%= render partial: "form", locals: { texto_da_acao: "Criar Departamento" } %>

app/views/departamentos/show.html.erb
<h1>Departamentos</h1>

<tr>
    <td><%= @departamento.nome %></td>
</tr><br>
<%= link_to "Criar novo departamento", new_departamento_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lojadecamisetas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar brand: "Loja Virtual", brand_link: root_url do %>
      <%= form_tag busca_produto_path, method: :get, class: "navbar-form navbar-right" do %>
        <div class="form-group">
          <%= text_field_tag :nome, @nome_a_buscar, class: "form-control" %>
          <%= button_to "Buscar", nil,  class: "btn btn-default"%>
        </div>
        <div class="form-group">
          <%= link_to "Departamentos", departamentos_path, class: "btn btn-default" %>
        </div>
      <% end %>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
    
  </body>

</html>

app/views/produtos/_form.html.erb
<% @produto.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert"><%= message %></div>
<% end %>

<%= form_for @produto do |form| %>
    <div class="form-group">
        <%= form.label :nome %>
        <%= form.text_field :nome, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :departamento%>
        <%= form.collection_select :departamento_id, @departamentos, :id, :nome, {}, class: "form-control" 
        %>
    </div>


    <div class="form-group">
        <%= form.label :descricao %>
        <%= form.text_area :descricao, class: "form-control", rows: 4 %>
    </div>
    <div class="form-group">
        <%= form.label :quantidade %>
        <%= form.number_field :quantidade, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= form.label :preco %>
        <%= form.number_field :preco, class: "form-control" %>
    </div>
    <%= form.submit texto_da_acao, class: "btn btn-primary" %>
<% end %>

app/views/produtos/_produto.html.erb
<tr>
<td><%=produto.nome%></td>
<td><%=produto.descricao%></td>
<td><%=produto.preco%></td>
<td><%= button_to "Remove", produto, method: :delete, class: "btn btn-danger", 
        data: {confirm: "Tem certeza que deseja remover #{produto.nome}?"} %></td>
<td>
    <%= link_to "Atualizar", edit_produto_path(produto), class: "btn btn-default"%>
</td>
</tr>

app/views/produtos/busca.html.erb
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
        </tr>
    </thead>
    <tbody>
        <%= render partial: "produto", collection: @produtos %>
    </tbody>
</table>

app/views/produtos/edit.html.erb
<%= render partial: "form", locals: { texto_da_acao: "Atualizar Produto" } %>

app/views/produtos/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
        </tr>
    </thead>
    <tbody>
        <%= render partial: "produto", collection: @produtos_por_nome %>
    </tbody>
</table>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
        </tr>
    </thead>
    <tbody>
        <%= render partial: "produto", collection: @produtos_por_preco %>
    </tbody>            
</table>
  

<%= link_to "Criar novo produto", new_produto_path, class: "btn btn-primary" %>

app/views/produtos/new.html.erb
<%= render partial: "form", locals: { texto_da_acao: "Criar Produto" } %>